[package]
name = "plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
extism-pdk = "1.3.0"
plist = "1.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shlex = "1.1.0"

[lib]
crate_type = ["cdylib"]
